- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/VerifiableCredentialTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/Passport.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/VerifiableCredential.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/helpers/JwtHelperTest.java
This PR is to mirror the changes on https://github.com/alphagov/di-ipv-cri-uk-passport-back/pull/256
Added icaoIssuerCode to passport Verifiable credential
As per VC spec listed here - https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0024-identity-vc-for-checks.md#document-validity-check
- [LIME-255](https://govukverify.atlassian.net/browse/LIME-255)
https://github.com/alphagov/di-ipv-cri-uk-passport-back/pull/256
[LIME-255]: https://govukverify.atlassian.net/browse/LIME-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-255 - Updating VC to include issuer code

- infrastructure/lambda/template.yaml
Issue: PLAT-789
Comment out VpcConfig from Global setup. 
A Lambda function always runs inside a VPC owned by the Lambda service. Lambda applies network access and security rules to this VPC and Lambda maintains and monitors the VPC automatically.
> PLAT-789-detach-vpc

- infrastructure/lambda/template.yaml
APIGatewayId as required by dns-records
Required by https://github.com/alphagov/di-ipv-cri-common-infrastructure/blob/main/dns-records/template.yaml#L82-L83
- [PLAT-833](https://govukverify.atlassian.net/browse/PLAT-833)
[PLAT-833]: https://govukverify.atlassian.net/browse/PLAT-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLAT-833 APIGatewayId as required by dns-records

- .github/workflows/checkov.yml
- .github/workflows/pre-merge-checks.yml
- build.gradle
- infrastructure/lambda/template.yaml
Re-enable cri-vpc with checkpassport now using protected subnets
Correct path used in checkov scan and set it to warn only.
Pre-merge checks ported from DL and updated.
cri-vpc was disabled to allow testing, when enabled the checkpassport lambda could not reach the thirdparty api when using the private subnets.
checkov scan path was pointed to the old template location and soft-fail added to warn and not fail until checkov is required.
To align passport with DL checks and an attempt (unsuccessfully) to correct sonar step warning about not find the *.java files in the cache.
- [LIME-409](https://govukverify.atlassian.net/browse/LIME-409)
[LIME-409]: https://govukverify.atlassian.net/browse/LIME-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-409 Re-enable cri-vpc, with checkpassport now using protected subnets

- infrastructure/lambda/template.yaml
VpcConfig set per lambda
Don't use CodeSigningConfigArn on dev
Global VpcConfig is override
Defaulting to "none" when the arn is not provided prevents deployment on dev as "none" not a valid arn format. Instead CodeSigningConfigArn now becomes AWS::NoValue on dev via a condition.
- [LIME-409](https://govukverify.atlassian.net/browse/LIME-409)
[LIME-409]: https://govukverify.atlassian.net/browse/LIME-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-409 Remove global VpcConfig and set VpcConfig per lambda

- infrastructure/lambda/template.yaml
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ParameterStoreParameters.java
- Third party API was wrapped in a conditional parameter for later refactoring.
- [LIME-475](https://govukverify.atlassian.net/browse/LIME-475)
[LIME-475]: https://govukverify.atlassian.net/browse/LIME-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
With current third party API:
Without:
> LIME-475 - Third party API logic wrapped in conditional parameter.

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportStepDefs.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/BrowserUtils.java
- acceptance-tests/src/test/resources/features/passport/Passport.feature
- acceptance-tests/src/test/resources/features/passport/WelshLangPassport.feature
Correct typo in cookeBanner in common-express
https://govukverify.atlassian.net/browse/LIME-633
Test added to validate the Reject analytics cookies and the correct sentence.
> Reject Analytics Cookie banner

- infrastructure/lambda/template.yaml
Enable code signing when CodeSigningConfigArn is set
Code signing previously default to off based on environment, with dev not requiring code signing.
Deployment into dev via pipeline needs signing enabled so the condition is changed.
- [LIME-619](https://govukverify.atlassian.net/browse/LIME-619)
[LIME-619]: https://govukverify.atlassian.net/browse/LIME-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-619 Enable code signing when CodeSigningConfigArn is set, default to no if not set

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportStepDefs.java
- acceptance-tests/src/test/resources/features/passport/Passport.feature
Remove the existing test step where we validate the expiry date as 6 months from the current date
Add a new test step to validate that the exp date field is no longer available in the VCs in Passport CRI
(https://govukverify.atlassian.net/browse/LIME-670)
> No Expiry in VC test added

- deploy.sh
- infrastructure/lambda/template.yaml
Per lambda VPC config based on presence of DevEnvironment=cri-dev override (default off)
Correct indentation in VpcConfig blocks
Moved the blocks below properties so indentation is clear
Add --lint to deploy.sh
Commented out IsProdLikeEnvironment condition
PR amended to place just check passport in the VPC and fix indentation on ProvisionedConcurrencyConfig sections
cri-dev uses a different vpc stack to that of the passport-v1's environments
VpcConfig indentation was incorrect (but no errors) and only detected by presence of the unused condition variable when --lint was used against the template before deploy. Otherwise only a manual check would show the VpcConfig was not applying
IsProdLikeEnvironment is unused and blocks deploy.sh due to --lint 
Only private gateways to be place in the …
> LIME-477 Allow VPC's to be applied in all environments

- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ThirdPartyAPIService.java
Add IOException logging to Thirdparty service
To debug connectivity with performance stub
- [LIME-477](https://govukverify.atlassian.net/browse/LIME-477)
[LIME-477]: https://govukverify.atlassian.net/browse/LIME-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-477 Add IOException logging to Thirdparty service

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ClientFactoryService.java
Fix unassigned SSLContext
SSLContext created for the stub path was not being used
- [LIME-477](https://govukverify.atlassian.net/browse/LIME-477)
[LIME-477]: https://govukverify.atlassian.net/browse/LIME-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-477 Fix unassigned SSLContext

- infrastructure/lambda/template.yaml
Increased provisioned concurrency in build
Increased memory in build
To align with production for performance testing
> LIME-698: Right sizing passport build to match production

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportAPIStepDefs.java
- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
API tests have been added to test the call to auth token from passport CRI and the call to HMPO from Passport CRI using GraphQL
> LIME-477 API tests to create call to auth token from passport cri

- .github/workflows/pre-merge-integration-test.yaml
- README.md
- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
- deploy.sh
- infrastructure/lambda/template.yaml
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationServiceTest.java
Add ParameterPrefix to template to allow using parameter store values from an existing stack (or manually created parameters under a prefix).
PARAMETER_PREFIX environment variable added so Java Lambdas can pickup the correct value.
Override placed in PassportConfigurationService for cri-lib/ConfigurationService/getParameterValue, to allow the parameter prefix to take effect in api code in place of the stackname.
Change API test to use passport-v1-cri-dev
Pre-merge test where unable to be ran with-out setting a growing number of thirdparty API secrets. The parameter prefix avoids maintaining these values in the actions.
Override for getParameterValue - placeholder until this can be moved to cri-lib. This follows the existing pattern for the secrets manager prefix but now for parameter …
> LIME-747 Add support for and enable pre-merge integration tests

- .github/workflows/pre-merge-integration-test.yaml
- deploy.sh
- infrastructure/lambda/template.yaml
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dcs/DcsThirdPartyAPIService.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/DocumentDataVerificationServiceTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/verifiablecredential/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/service/VerifiableCredentialServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/HttpRequestConfig.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/DocumentCheckResultItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ServiceFactory.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationServiceTest.java
Added check details and failed check details to the passport VC
Add support to always get specific parameters from the current stack, irrespective of prefix override.
Added fix for api-keys and usage plans being enabled in manual deployments.
Added fix for slow first reply on imposter stub.
To allow the VC to indicate what makes up the score and CIs
Some parameters should not be overriden and always be from or set via the deployed stack.
API key usage policies where being enforced in dev limiting the number of dev stacks.
The timeout on first read from the socket has increased to 10 secs to give the stub time to read its config from the s3 bucket. The stub Lamdba has provisioned concurrency but reads the s3 bucket when starting a new execution context.
> LIME-629: Added check details and failed check details to the passport VC

- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
- acceptance-tests/src/test/resources/features/passport/WelshLangPassport.feature
…r summary
Updated a Welsh language test 'Passport details Name field error message in Welsh' to return the expected middle names error summary text in Welsh.
Also, commented out an API test 'Passport details Name field error message in Welsh' for hmpoDVAD. This test is currently failing as an incorrect validity score is being returned. A bug LIME-776 has been raised to fix this issue and this will be retested when the bug has been fixed.
> LIME-745-Re-run-regression-tests-for-PassportV1

- acceptance-tests/build.gradle
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/UniversalStepDefs.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/BrowserUtils.java
- acceptance-tests/src/test/resources/features/passport/Passport.feature
- acceptance-tests/src/test/resources/features/passport/WelshLangPassport.feature
Added steps to set the feature based upon the tag currently being run
To allow us to reuse our existing test pack to test the new direct connection work via a feature set
> LIME-487: Small updated to use the active tag to identify which feature set to run the tests against

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/UniversalSteps.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportStepDefs.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/UniversalStepDefs.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/BrowserUtils.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/TestDataCreator.java
- acceptance-tests/src/test/resources/features/passport/Passport.feature
- acceptance-tests/src/test/resources/features/passport/WelshLangPassport.feature
- acceptance-tests/src/test/resources/log4j2.xml
AC Test failures
Anywhere where a page title is asserted there is now a 2 second wait added just before the 
asserting.
The same is done, where a URL is asserted.
Testusers
Config for Kenneth being referred to as Billy 
Logging
Fixed there being no log4j config.output.
Replaced log lines using the internal java logging with the log4j logger.
Feature set
Added extra checking to setting of the feature set.
AC test failures
Randomly a page may have a delay loading, or a test may run faster than expected and the title assert (or URL assert) would fail due to finding an empty page or not having started loading.
Several methods asserting page titles are combined into one, so there is one place where the delay is added.
Testuser
Billy is a separate test user in DL.
Logging
Config added to allow …
> LIME-489 Fix random errors in tests, fix test user crosswired, fix test logging not working

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
- acceptance-tests/src/test/resources/features/passport/E2E_Passport.feature
- acceptance-tests/src/test/resources/features/passport/WelshLangPassport.feature
The incorrect date of birth error validation tests in Welsh have been updated.
The E2E tests have been updated to use the correct test user 'PassportSubjectHappyKenneth'
These changes have been done as part of LIME-637.
> LIME-637-updated welsh lang incorrect DOB tests and E2E tests

- acceptance-tests/run-tests.sh
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/model/PassportFormData.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportAPIStepDefs.java
- acceptance-tests/src/test/resources/Data/PassportAlexandraElegbaDCSOnlyJsonPayload.json
- acceptance-tests/src/test/resources/features/passport/Passport.feature
- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/metrics/Definitions.java
Updated passport handler to perform the document check again if HMPO returns either a failure or an exception is thrown
To ensure when switching to HMPO that no users are effected if an error presents
- [LIME-809](https://govukverify.atlassian.net/browse/LIME-809)
[LIME-809]: https://govukverify.atlassian.net/browse/LIME-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-809: Added fallback functionality so that if HMPO fails we fallback to DCS checks

- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
Added an API test to validate that Passport CRI returns ci as D02 in the passport vc when there is no match and the document checking route is DVAD. This test was added as part of testing LIME-811.
> lime-811-D02-mappings-testing

- infrastructure/lambda/template.yaml
Replicated Driving licence concurrent executions alarms for Passport
To allow alerting if lambda concurrency is above the typically expected levels
- [LIME-820](https://govukverify.atlassian.net/browse/LIME-820)
[LIME-820]: https://govukverify.atlassian.net/browse/LIME-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-820 Replicate Driving licence concurrent executions alarms in Passport

- acceptance-tests/src/test/resources/features/passport/Passport.feature
- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
Removed the fail over logic and tests from the passport CRI
Changed as the passport CRI has been running successfully for over a week now
> LIME-830: Removing fail over logic from the passport CRI

- infrastructure/lambda/template.yaml
Removed 4XX alarm from template
So that we are no longer running P1 alerts for 400's in production
> LIME-862: Removed 4XX alarm and tidied the alerts to align with other CRIs

- README.md
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportAPIStepDefs.java
- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/domain/result/DocumentDataVerificationResult.java
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/domain/result/fields/ContraIndicatorMapperResult.java
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ContraIndicatorComplexMapping.java
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ContraIndicatorMapper.java
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/DocumentDataVerificationService.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ContraIndicatorComplexMappingTest.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ContraindicationMappingsTest.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/DocumentDataVerificationServiceTest.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dvad/DvadThirdPartyAPIServiceTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/CiReasons.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/checkdetails/Check.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/verifiablecredential/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/util/EvidenceHelper.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/service/VerifiableCredentialServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/CheckType.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/DocumentCheckResultItem.java
- lib/src/testFixtures/java/uk/gov/di/ipv/cri/passport/library/DocumentCheckTestDataGenerator.java
Reworked ContraIndicatorMapper to handle the processing of CI's, CI Reasons, Checks and failed checks for response flags. As part of the CI Mapping format changed.
Removed document-check route header from pre-merge tests (not longer used)
Pre-merge tests updated and aligned with flag obfuscation.
Update readme for aws vault usage
ContraIndicatorMapper reworked as this was the best place to handle the mapping, but needed support added to handle conditional appearance of CI reasons, with out reference to any response flags by name in code.
Document-check route header removal from tests -DVA-Direct only route used, with DCS is currently being decommissioned.
Pre-merge tests previously assert evidence content by String, this is now done via expected hashes based on numbered scenarios - to …
> LIME-832 VC/Audit Event Update - ciReasons and checkDetails/failedCheckDetails

- infrastructure/lambda/template.yaml
Increase api rate/burst limits and lambda cpu allocation.
Moved some value maps.
Align Passport API with DLAPI values
Value maps moved to allow 3-way diff between templates to line up.
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-727 Increase Passport API Throttle/Throttling limits

- .github/workflows/post-merge-deploy-to-dev.yml
Fix deploy to dev action failure.
deploy to dev was hardcoded to gradle 7.6 - switched to wrapper version
- [LIME-844](https://govukverify.atlassian.net/browse/LIME-844)
[LIME-844]: https://govukverify.atlassian.net/browse/LIME-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-844 Fix deploy to dev action failure

- .github/workflows/dailyPassportSmokeTest.yml
- acceptance-tests/build.gradle
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/UniversalSteps.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportStepDefs.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/Driver.java
Fix smoke tests via using the wrapper vs gradle directly
- Added note to update the following cucumber_version, selenium_version and webdrivermanager_version together
- Updated cucumber_version, selenium_version and webdrivermanager_version
- Fixed race condition for page title assertions via waitForPageToLoad
- Fix setHeadless removal
- Added "with gradle-version: wrapper" to setup gradle action
- [LIME-991](https://govukverify.atlassian.net/browse/LIME-991)
[LIME-991]: https://govukverify.atlassian.net/browse/LIME-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-991-smoke - Fix smoke tests via using the wrapper vs gradle directly

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/UniversalSteps.java
- acceptance-tests/src/test/resources/features/passport/English/Passport.feature
The following tests have been fixed
1) Scenario name : Passport User cancels before first attempt via prove your identity another way route
Test step 'User selects prove another way radio button' has been removed from the test and navigateToPassportResponse() method has been updated.
2) Scenario name : Passport details IncorrectDateOfBirth error message in Welsh
Scenario name : Passport Valid until date field error message in Welsh
The web element on the method for test step 'the validation text reads Mae problem' has been updated on both the tests.
> LIME-1049 Fix the tests that are failing in Passport CRI

- .github/dependabot.yml
- .github/workflows/dailyPassportSmokeTest.yml
- .github/workflows/pre-merge-checks.yml
- .github/workflows/pre-merge-integration-test.yaml
Workflow dispatch has been added to the pre-merge check files.
Dependabot is unable to build successfully because it does not have access to secrets. This change should allow us to get builds to pass so we can reliably merge dependabot PRs.
- [LIME-842](https://govukverify.atlassian.net/browse/LIME-842)
[LIME-842]: https://govukverify.atlassian.net/browse/LIME-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-842 adding workflow dispatch

- infrastructure/lambda/template.yaml
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ThirdPartyAPIServiceFactory.java
- Removed Performance Stub in use environment variable so that tls on/off is dependent on test strategy route
> LIME-983 - Removing tlsOn Environment variable

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/BrowserUtils.java
The value of "lang" has been edited to "lng" in acceptance-tests.
The value has been changed in common-express. As our front end was changed for the language toggle, this change is required for our api tests to be aligned for this value. 
- [LIME-1069](https://govukverify.atlassian.net/browse/LIME-1069)
[LIME-1069]: https://govukverify.atlassian.net/browse/LIME-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1069 aligning lng cookie value in tests

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
Updated page objects to match new stub buttons for passport
Old stub page objects were outdated
- [LIME-1120](https://govukverify.atlassian.net/browse/LIME-1120)
[LIME-1120]: https://govukverify.atlassian.net/browse/LIME-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1120 - Updated stub passport page objects

- .github/workflows/secure-post-merge.yml
Removed obsolete and redundant rusty-actions workflow step
This is obsolete and now handled by the dev-platform upload action. Replacing previous PR (https://github.com/govuk-one-login/ipv-cri-uk-passport-api/pull/88)
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
[IPS-503]: https://govukverify.atlassian.net/browse/IPS-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ips-503 remove rusty action

- .github/workflows/pre-merge-checks.yml
- .pre-commit-config.yaml
- .secrets.baseline
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
- lib-dvad/src/main/java/uk/gov/di/ipv/cri/passport/library/dvad/domain/response/RequestHeaderKeys.java
- lib-dvad/src/main/java/uk/gov/di/ipv/cri/passport/library/dvad/services/DvadAPIHeaderValues.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ParameterStoreParameters.java
- Added pre-commit GHA workflow
-  Updated pre-commit-config with `detect-secrets`
- Added secrets.baseline
- As per ticket requirements
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-487: Add pre-commit GHA workflow and update pre-commit-config

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
Removing a field which was added to fix a test three weeks ago.
This may be responsible for breaking the passport pipeline.
- [LIME-1140](https://govukverify.atlassian.net/browse/LIME-1140)
[LIME-1140]: https://govukverify.atlassian.net/browse/LIME-1140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1140 fixing failing test

- .github/workflows/post-merge-package-for-build.yml
Correct secret name used for artifact-bucket-name in upload action
Secret is named differently for passport
- [LIME-843](https://govukverify.atlassian.net/browse/LIME-843)
[LIME-843]: https://govukverify.atlassian.net/browse/LIME-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-843 correct deploy to build bucket

- .github/workflows/run-pre-merge-integration-tests.yml
- .github/workflows/smoke-test-build.yml
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/runners/TestRunner.java
- acceptance-tests/src/test/resources/cucumber.properties
Disabled auto-reporting via the following 
Add cucumber.properties with the following contents
- cucumber.publish.quiet=false to ensure reporting if re-enabled is visible
- cucumber.publish.enabled=false to stop the reporting.
Removed env-var CUCUMBER_PUBLISH_ENABLED: true from git hub actions
Change publish to false in @CucumberOptions in the test runner.
To disable sending reports to a third-party
- [LIME-1212](https://govukverify.atlassian.net/browse/LIME-1212)
[LIME-1212]: https://govukverify.atlassian.net/browse/LIME-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1212 Disable cucumber report publishing

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/runners/TestRunner.java
- acceptance-tests/src/test/resources/cucumber.properties
Remove cucumber publish variable
A previous PR set the publish value to false to disable the report publishing.
The presence of the variable is however is still being flagged.
- [LIME-1212](https://govukverify.atlassian.net/browse/LIME-1212)
[LIME-1212]: https://govukverify.atlassian.net/browse/LIME-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1212 Remove references to cucumber publish

- .github/workflows/run-sonar-scan.yml
- .github/workflows/run-unit-tests.yml
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java
- build.gradle
- infrastructure/lambda/template.yaml
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/utils/PreLambdaHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/service/VerifiableCredentialServiceTest.java
Updated verifiableCredentialService to use updated jwtSigning implementation and include kid in jwt headers
> LIME-1201 - Including Opaque KID in JWT headers for VCs

- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/handler/IssueCredentialHandlerTest.java
Add null session_id check to lambda handlers in passport CRI.
Added null check to CheckPassportHandler and IssueCredentialHandler to throw a SessionNotFoundException if a session is not found in the header.
Relevant unit test were added to CheckPassportHandlerTest and  IssueCredentialHandlerTest to maintain code coverage.
Fix for bug where the session could be passed in as null from the front end. 
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
PR for equivalent changes in dl CRI has been completed [here](https://github.com/govuk-one-login/ipv-cri-dl-api/pull/234)
PR for equivalent changes in fraud CRI has been completed [here](https://github.com/govuk-one-login/ipv-cri-fraud-api/pull/326)
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoi …
> [LIME-1114] Added check for incoming session_id header is not null

- build.gradle
- lib-dvad/src/main/java/uk/gov/di/ipv/cri/passport/library/dvad/services/DVADCloseableHttpClientFactory.java
Updated intermediate and cert values for HMPO DVAD non prod
As the previous certificates were due to expire
> LIME-1281: Updated certificates for HMPO cert rotation non prod

- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
Issue during testing where an empty value for the session_id header was returning Unexpected server error.
Update CheckPassportHandler.java to use UUID so it catches incorrect strings/special chars
Added UUID check for sessionID in CheckPassportHandler.java 
Added unit test for invalid sessionID in CheckPassportHandlerTest.java 
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
- [LIME-1289](https://govukverify.atlassian.net/browse/LIME-1289)
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1289]: https://govukverify.atlassian.net/browse/LIME-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIME-1114] Added sessionID validation UUID check

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportAPIStepDefs.java
- acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
to check that when a invalid sessionid is sent to the driving licence endpoint, or authcode is sent in credential issuer endpoint
Added new acceptance-tests to Passport Api tests
To add coverage to the changes made in LIME-1114 around incoming session_id header is not null
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
New Test added:
New Test Passing locally in Dev: 
Pre-merge test passing locally in Dev:
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1114: Added new API Acceptance tests

- acceptance-tests/run-dev-perf-test.sh
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/UniversalSteps.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/UniversalStepDefs.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/Driver.java
Add dev perf test script.
Correctly clean up after each ac test.
Add error page logging (from DL ac test)
To allow a faster build and test iteration with-out involving a full formal perf test.
Ac test where leaving the driver open, leaving lots of browsers open after the test.
This change closes the driver after each test using in built cucumber support.
Error page logging was useful in DL to locate error source.
- [LIME-1208](https://govukverify.atlassian.net/browse/LIME-1208)
[LIME-1208]: https://govukverify.atlassian.net/browse/LIME-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1208 Add dev perf test script and correctly clean up each ac test

- infrastructure/lambda/template.yaml
Ensure automated passport CRI certificate expiration alerts are sent to the correct slack channel
Updated CertExpiryReminderFunctionPermission in template.yaml
changes allowed eventbridge rule to trigger certExpiry lambda function.
- [LIME-1282](https://govukverify.atlassian.net/browse/LIME-1282)
[LIME-1282]: https://govukverify.atlassian.net/browse/LIME-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1282 cert expiry permission corrected

- .secrets.baseline
- build.gradle
- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
- lambdas/certexpiryreminder/build.gradle
- lambdas/checkpassport/build.gradle
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/handler/IssueCredentialHandler.java
- lib-dvad/build.gradle
- lib/build.gradle
- SnapStartMapping added to enable snap-start role out only to specific environments to allow more testing prior to production role out.
- Moves all Passport lambda invocation paths and permissions to use the live alias
- - Cert Reminder event rule also updated
- Excludes unneeded url-connection-client aws dependancy in build.gradle files.
- Primes the DynamoDB Client during snap start.
- - This enables snap start to capture some more classes.
- - And avoid the DynamoDB client being initialised during the first request saving some time
To enable snap-start on all Passport CRI internal lambdas.
- [LIME-1384](https://govukverify.atlassian.net/browse/LIME-1384)
[LIME-1384]: https://govukverify.atlassian.net/browse/LIME-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> LIME-1384 Add Support allow enabling snap-start on all CRI Lambdas.

- infrastructure/lambda/template.yaml
Disable ProvisionedConcurrency in build add AutoPublishAliasAllProperties to help ensure lambda versions are published
ProvisionedConcurrency was not enable in the CRI until recently.
This reverts that change for just the build environment to allow a performance test as the CRI was configured then.
- [LIME-1384](https://govukverify.atlassian.net/browse/LIME-1384)
- [DCP-4141](https://govukverify.atlassian.net/browse/DCP-4141)
[LIME-1384]: https://govukverify.atlassian.net/browse/LIME-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCP-4141]: https://govukverify.atlassian.net/browse/DCP-4141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1384 Disable ProvisionedConcurrency in build add AutoPublishAliasAllProperties

- infrastructure/lambda/template.yaml
Re-enable ProvisionedConcurrency in build
To enable a performance test with ProvisionedConcurrency
- [LIME-1436](https://govukverify.atlassian.net/browse/LIME-1436)
[LIME-1436]: https://govukverify.atlassian.net/browse/LIME-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1436 Re-enable ProvisionedConcurrency in build

- infrastructure/lambda/template.yaml
Enable snap-start for Passport CRI (dev-staging)
To test snap-start prior to production roll out
- [LIME-1437](https://govukverify.atlassian.net/browse/LIME-1437)
[LIME-1437]: https://govukverify.atlassian.net/browse/LIME-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1437 Enable snap-start for Passport CRI (dev-staging)

- acceptance-tests/build.gradle
- build.gradle
- lambdas/certexpiryreminder/build.gradle
- lambdas/checkpassport/build.gradle
- lambdas/issuecredential/build.gradle
- lib-dvad/build.gradle
The purpose of this change would be to reduce the number of Nimbus dependencies that require updating and to remove the risk of conflict that exists in having a dependency that is already a sub-dependency.
removed jwt_version from build.gradle
- [LIME-1291](https://govukverify.atlassian.net/browse/LIME-1291)
[LIME-1291]: https://govukverify.atlassian.net/browse/LIME-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1291 Consolidate Nimbus dependencies

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- acceptance-tests/Dockerfile-traffictest
- acceptance-tests/traffic-tests/run-tests.sh
Traffic tests have been added as they are needed for canary work.
Existing acceptance test has been used for this and moved to a separate ecr for traffic tests.
Further work will focus on passing more traffic through the deployment stage, currently this traffic test invokes each lambda only once. 
Canary deployments means there are two versions of an application. To check backwards compatibility, traffic tests can be used in lower environments. This prevents backwards incompatible versions reaching production and issues only being discovered in production.
- [IPS-1240](https://govukverify.atlassian.net/browse/IPS-1240)
GH secrets added, these are the TestRunnerImageEcrRepositoryName values taken from traffic test repo:
ECR_REPOSITORY_TRAFFIC_TEST_DEV
ECR_REPOSITORY_TRAFFIC_TEST_BUILD
Test …
> Ips 1240 traffic test

- .secrets.baseline
- README.md
- infrastructure/lambda/template.yaml
Updated the template to allow for the lambda canary deployments.
Updated the public and private API configurations to target the live alias
LambdaDeploymentPreference default set to AllAtOnce (strategy will be overridden by parameter set in the pipeline)
Conditional added to only deploy and use canary alarms if canary strategy is not AllAtOnce
Lambda permission to invoke on Alias to enable apigw to invoke the live alias version of the lambda
5xx and lambda canary alarms added - set to trigger if one error occurs
Code deploy role added
To enable the passport lambda canary deployments
- [IPS-1104](https://govukverify.atlassian.net/browse/IPS-1104)
Canary deployment using linear strategy:
traffic shifted successfully
2 live versions whilst canary deployment is taking place:
Rollback when …
> IPS-1104 passport lambda canary deployments

- infrastructure/lambda/template.yaml
ActionsEnabled in canary alarms set to true from false
Originally set to false to stop alerts going to slack when the alarm is created in each environment. As the alarms are created now, the alarm won't be triggered.
- [IPS-1104](https://govukverify.atlassian.net/browse/IPS-1104)
[IPS-1104]: https://govukverify.atlassian.net/browse/IPS-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1104 ActionsEnabled set to true for new canary alarms

- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java
Remove DynamoDB Client initialisation from snap-start snap-shot
Disabled as it will be caching connection state that will only be valid for a short period after the snap-shot.
- [LIME-1437](https://govukverify.atlassian.net/browse/LIME-1437)
[LIME-1437]: https://govukverify.atlassian.net/browse/LIME-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1437 Remove DynamoDB Client initialisation from snap-start snap-shot

- infrastructure/lambda/template.yaml
Remove ProvisionedConcurrency from integration and production
To allow switching to a snap-start configuration
- [LIME-1521](https://govukverify.atlassian.net/browse/LIME-1521)
[LIME-1521]: https://govukverify.atlassian.net/browse/LIME-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1521 Remove ProvisionedConcurrency from integration and production

- .github/dependabot.yml
Changes made to:
1. Update grouping in dependabot.yml to ensure dependencies that are required to be kept at the same version number as each other are updated together by dependabot automatically rather than creating an individual PR for each dependency.  
2. Update dependabot open PR limit to 20 due to present limit of 5 being too few given some PRs can be blocked for some time. 
- [LIME-1229](https://govukverify.atlassian.net/browse/LIME-1229)
[LIME-1229]: https://govukverify.atlassian.net/browse/LIME-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1229 updates dependabot grouping and PR limit

- acceptance-tests/src/test/resources/features/passport/English/Passport.feature
- acceptance-tests/src/test/resources/features/passport/English/PassportFullJourneyfeature.feature
- acceptance-tests/src/test/resources/features/passport/Welsh/WelshLangPassport.feature
1591 - serviceName amended to remove _"... - Prove your identity" from page tab titles in DL FE. BE tests updated to reflect this and the adding of 'One Login' to the pageTitle suffix brought in by the Common Express update.
1578 - In addition, one test was uncommented in relation to a separate ticket (1578). This _'Check the Unrecoverable error/ Unknown error in Passport CRI'_ test was commented out whilst a fix was sort for it failing. This has now been resolved as a result of the update to common express 10.3.0 so the test can be added back in. 
To keep this service in line with other services of the programme and fix failing tests as a result of the Common Express update beyond 10.1.x.
- [LIME-1591](https://govukverify.atlassian.net/browse/LIME-1591)
- …
> Lime 1591 - Amended tests to account for updated pageTitle and unknown error test uncommented

- infrastructure/lambda/template.yaml
Prod and non-prod alarms differentiated in order to direct non-prod alarms to the lime-critical-alarm-nonprod Slack channel. 
- [LIME-941](https://govukverify.atlassian.net/browse/LIME-941)
[LIME-941]: https://govukverify.atlassian.net/browse/LIME-941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-941 prod and non-prod alarms differentiated

- .github/workflows/deploy-branch.yml
- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/run-pre-merge-integration-tests.yml
Pin sam cli version in pre and post merge to the same version.
To control the cadence of updates
- [LIME-1603](https://govukverify.atlassian.net/browse/LIME-1603)
[LIME-1603]: https://govukverify.atlassian.net/browse/LIME-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1603 Pin sam cli version in pre and post merge to the same version.

- .secrets.baseline
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
Specified /.well-known/jwks.json definition in the public.api template
JWKSBucketRole required to access the S3 bucket via the endpoint has been added to the lambda infrastructure template
To allow Core Stub to retrieve the active public key for encryption as part of the passport pilot.  A /well-known/jwks endpoint has been configured in the passport CRI API.
- [LIME-1592](https://govukverify.atlassian.net/browse/LIME-1592)
Rebase, address final comment + commits signed - smsgds
[LIME-1592]: https://govukverify.atlassian.net/browse/LIME-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1592 Specified well-known/jwks endpoint for passport pilot

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/Strategy.java
Add support for new ipv-core client id - "ipv-core-3rd-party-stubs"
Fix pre-merge sam build step missing sam-version: "1.134.0" pinning
ipv-core-3rd-party-stubs - To enable an IPV-Core end to end journey with CRI using third-party stubs
- [LIME-1626](https://govukverify.atlassian.net/browse/LIME-1626)
- depends on https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/441
[LIME-1626]: https://govukverify.atlassian.net/browse/LIME-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1626 Add support for new ipv-core client id - "ipv-core-3rd-party-stubs"

- infrastructure/lambda/template.yaml
-  Add `key_consumer_type=use` tag to APIGW role
- The bucket policy is conditional upon tags: https://github.com/govuk-one-login/ipv-cri-common-infrastructure/pull/109
- [IPS-1529](https://govukverify.atlassian.net/browse/IPS-1529)
[IPS-1529]: https://govukverify.atlassian.net/browse/IPS-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1529: Add tag to passport role

- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
- Updated bucket name
- Minimise probability of the bucket name being taken, as all S3 bucket names must be globally unique
- [IPS-1633](https://govukverify.atlassian.net/browse/IPS-1633)
[IPS-1633]: https://govukverify.atlassian.net/browse/IPS-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1633: Update bucket name

- infrastructure/lambda/template.yaml
Implement an alarm that alerts when no key alias available to the CRI matches the encryption key used to create the encrypted payload it received from a client (Core/Core Stub).
Metric has been added to session lambda (all_aliases_unavailable_for_decryption).
- Alarm config added to template
- Thresholds are low given the critical nature of the failure
- Alarm state testing attached to the ticket
- [LIME-1630](https://govukverify.atlassian.net/browse/LIME-1630)
[LIME-1630]: https://govukverify.atlassian.net/browse/LIME-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1630 OAuth Pilot | Alarm for alias-based decryption failure

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java
- acceptance-tests/src/test/resources/features/passport/English/Passport.feature
- build.gradle
Update to CRI-Lib 5.2.1
To bring in retries on getSessionByAccessToken
- [LIME-1683](https://govukverify.atlassian.net/browse/LIME-1683)
[LIME-1683]: https://govukverify.atlassian.net/browse/LIME-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1683 Update to CRI-Lib 5.2.1

- .secrets.baseline
- infrastructure/lambda/template.yaml
Disable alarms in non-pipeline stacks 
To reduce alarm notification noise
- [LIME-1665](https://govukverify.atlassian.net/browse/LIME-1665)
[LIME-1665]: https://govukverify.atlassian.net/browse/LIME-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1665 Disable alarms in non-pipeline stacks to reduce alarm notification noise

- .github/workflows/cleanup-pre-merge-stacks.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/run-pre-merge-integration-tests.yml
- deploy.sh
- infrastructure/lambda/template.yaml
Correct base-dir not being set to the correct directory
Fix pre-merge stacks being left around
Space out some actions steps to aid readablity
Rename Get stack name vars to Get output variables, as it is now doing more than just the short sha
Store the checked out repo location in the output repo_base_dir to enable providing a full path as base-dir in the sam build action
Base-dir if not set defaults to the template location.
This leaves sam build unable to find gradlew expecting the template to be in the project root directory. sam build the fall back to using gradle from the system PATH.
pre-merge stacks had no cleanup action, so if the step to delete them failed they stay around.
Several step actions where very condensed leading to readability issues.
Renaming to make clear the step …
> LIME-1826 - Correct base-dir not being set to the correct directory

- .secrets.baseline
- infrastructure/lambda/template.yaml
Change Dynatrace OneAgent Layer arn to a version based path for Passport API.
Dynatrace OneAgent Layer first needs to resolve to v1_311 before then updating the version to v1_311.
- [LIME-1811](https://govukverify.atlassian.net/browse/LIME-1811)
[LIME-1811]: https://govukverify.atlassian.net/browse/LIME-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lime 1811: Update Dynatrace OneAgent Layer to v1_311_51_20250331-143707.

- infrastructure/lambda/template.yaml
Directed the prod cert expiry alarm away from di-2nd-line channel as this has been firing daily and producing pager duty notifications for a cert that will expire in 20+ days. This alarm would continue firing daily until the certs are rotated without this change taking place. 
Once the certs are rotated, consideration will be given to reverting this change or leaving as is. This has been noted in the cert rotation ticket scope for https://govukverify.atlassian.net/browse/LIME-1757. 
- [LIME-1834](https://govukverify.atlassian.net/browse/LIME-1834)
Evidence in ticket
[LIME-1834]: https://govukverify.atlassian.net/browse/LIME-1834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1834 redirect cert expiry alarm away from di-2nd-line

- .github/workflows/post-merge-package-for-build.yml
- .pre-commit-config.yaml
Removing manual github actions trigger for a deploy to build.
Could erroneously deploy a branch to build which could propagate up to prod.
- [LIME-1845](https://govukverify.atlassian.net/browse/LIME-1845)
Updated checkov patch version to run pre-commit hooks.
[LIME-1845]: https://govukverify.atlassian.net/browse/LIME-1845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1845: Remove manual trigger for package for build github actions pipeline
