.github/workflows/secure-post-merge.yml
Enabling temporarily while testing the pipeline, to be removed later
Issue: PLAT-788
Co-authored-by:
=> PLAT-788 Add workflow_dispatch to publish GHA

lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationServiceTest.java
Fix unit failing unit test, due to using an incorrect ssm parameter path.
Failing test will block testing pipeline promotion.
- [LIME-407](https://govukverify.atlassian.net/browse/LIME-407)
[LIME-407]: https://govukverify.atlassian.net/browse/LIME-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-407 Fix failing unit test

infrastructure/lambda/template.yaml
Removed code signing enabled condition 
presence of an arn should determine if signing is required or not
=> LIME-409: Removed code signing enabled feature this should be controlled by the presence of an arn

acceptance-tests/src/test/resources/features/passport/WelshLangPassport.feature
updated tests to reflect the translation changes in the FE PR
https://github.com/alphagov/di-ipv-cri-uk-passport-front-v1/pull/10
=> LIME-669 Updating welsh translation tests

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/secure-post-merge.yml
Add post merge deploy to dev action 
To allow pushing latest code into dev
- [LIME-619](https://govukverify.atlassian.net/browse/LIME-619)
[LIME-619]: https://govukverify.atlassian.net/browse/LIME-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-619 Add post merge deploy to dev

infrastructure/lambda/template.yaml, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ThirdPartyAPIService.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ClientFactoryService.java
Added feature toggle to disable ssl and adding logging
To allow performance testing on the environments
=> LIME-697: Adding functionality to enable performance testing

.github/workflows/pre-merge-integration-test.yaml, deploy.sh, infrastructure/lambda/template.yaml, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/HttpRequestConfig.java
Removed assumption of the environment "dev" being a safe determination on configuration of resources.
Removed IsDevEnvironment/IsNotDevEnvironment and replaced with IsDeployedFromPipeline.
IsDeployedFromPipeline can be toggled with the DeploymentType parameter override.
DeploymentType defaults to pipeline which enables the protected setup.
Replaced the use of IsDevEnvironment condition used to avoid creating the environment wide release-flag `vc-expiry-removed` in dev. Replaced it with a specific condition OverrideSettingOfEnvironmentWideFeatureFlag and added a comment that this condition can be removed when the feature is permanent. The override is needed as the parameter will be owned by the first stack to create it and prevent multiple devs deploying stacks.
Add placeholder condition …
=> LIME-688 Remove IsDevEnvironment/IsNotDevEnvironment conditionals and use IsDeployedFromPipeline for configuration of resources

README.md
Updated Readme
Readme was missing deployment information for new environments and gradle tasks.
- [LIME-742](https://govukverify.atlassian.net/browse/LIME-742)
[LIME-742]: https://govukverify.atlassian.net/browse/LIME-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-742 Update Readme

acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportAPIStepDefs.java, acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
Added additional AC test steps
To ensure VCs always have check details array
=> LIME-629: Added additional AC test steps to cover check details

.cfnlintrc, .pre-commit-config.yaml, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java, deploy.sh, infrastructure/lambda/template.yaml
Uncommented Pager Duty parameter alerts in template and added pager duty parameters in all environments.
Added a fix for test for local deployment
To allow alarms to be triggered.
To be able to test for local deployment
=> LIME-735 - Uncommented Pager Duty parameter alerts in the template and added a fix for tests for local deployment 

infrastructure/lambda/template.yaml
Enabling pushing of logs to splunk for new passport
Uncommented the CSLS settings
As we are approaching go live we now need to confirm logs are pushing to splunk correctly
=> LIME-802: Enabling splunk logs for new passport

.github/workflows/pre-merge-checks.yml
BAU Sonarcloud run on main
modified:   .github/workflows/pre-merge-checks.yml
=> BAU Sonarcloud run on main

acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java, infrastructure/lambda/template.yaml, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
Removed feature set functionality and toggled on DVAD
To switch passport to DVAD in the production accounts
=> LIME-609: Toggling on DVAD across all environments

acceptance-tests/src/test/resources/Data/PassportInvalidCI1JsonPayload.json, acceptance-tests/src/test/resources/Data/PassportInvalidCI2JsonPayload.json, acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandler.java, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/DocumentDataVerificationService.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java
Added additional logging
Added functionality to trigger fallback on CI
To make tracking passport flags easier and ensure they are mapped correctly
=> LIME-827: Updating logging and ensuring CIs trigger fallback

acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
Fixing test and fallback to facilitate D01 mapping
- [LIME-825](https://govukverify.atlassian.net/browse/LIME-825)
[LIME-825]: https://govukverify.atlassian.net/browse/LIME-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-825 Mapping D01 for passport

build.gradle
IPS-310 Sonarcloud Migration
IPS-310 Sonarcloud Migration
- [IPS-310](https://govukverify.atlassian.net/browse/IPS-310)
[IPS-310]: https://govukverify.atlassian.net/browse/IPS-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-310 Sonarcloud Migration to govuk-one-login

.github/workflows/pre-merge-checks.yml, acceptance-tests/build.gradle, build.gradle, dependencyCheckAnalyzeSuppressionFiles/Netty-CVE-2023-4586.xml
Several dependency versions have been increased, a new release of common-libs has been added and added the ability to scan for vulnerabilities 
To remove security vulnerabilities in our code
- [LIME-823](https://govukverify.atlassian.net/browse/LIME-823)
[LIME-823]: https://govukverify.atlassian.net/browse/LIME-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Lime 823 Address security issues on Passport V1

dependencyCheckAnalyzeSuppressionFiles/Netty-CVE-2023-4586.xml, infrastructure/lambda/template.yaml
IPS-289 add changes for dynatrace integration
IPS-289 add changes for dynatrace integration
- [IPS-289](https://govukverify.atlassian.net/browse/IPS-289)
[IPS-289]: https://govukverify.atlassian.net/browse/IPS-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-289 add changes for dynatrace integration

infrastructure/lambda/template.yaml
BAU Revert Dynatrace Implementation
BAU Revert Dynatrace Implementation
=> BAU Revert Dynatrace Implementation

infrastructure/lambda/template.yaml
Re-introduce IPS-289 add changes for dynatrace integration
IPS-289 add changes for dynatrace integration
- [IPS-289](https://govukverify.atlassian.net/browse/IPS-289)
- Re-application post VPC update
[IPS-289]: https://govukverify.atlassian.net/browse/IPS-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-289 re-introduce changes for dynatrace integration

build.gradle, infrastructure/lambda/template.yaml, lambdas/certexpiryreminder/build.gradle, lambdas/certexpiryreminder/src/main/java/uk/gov/di/ipv/cri/passport/certexpiryreminder/handler/CertExpiryReminderHandler.java, lambdas/certexpiryreminder/src/main/resources/log4j2.xml, lambdas/certexpiryreminder/src/test/java/uk/gov/di/ipv/cri/passport/certexpiryreminder/handler/CertExpiryReminderHandlerTest.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/metrics/Definitions.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationService.java, lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationServiceTest.java, settings.gradle
Created certificate expiry reminder lambda
=> LIME-498 - Creating certificate expiry reminder lamdba

.github/workflows/dailyPassportSmokeTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/pre-merge-integration-test.yaml, .github/workflows/secure-post-merge.yml, .sdkmanrc, README.md, acceptance-tests/Dockerfile, acceptance-tests/build.gradle, build.gradle, gradle.properties, infrastructure/lambda/template.yaml, lambdas/certexpiryreminder/build.gradle, lambdas/checkpassport/build.gradle, lambdas/issuecredential/build.gradle, lib/build.gradle
Upgrade passport-api to java17
- [LIME-844](https://govukverify.atlassian.net/browse/LIME-844)
[LIME-844]: https://govukverify.atlassian.net/browse/LIME-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-844 Upgrade passport-api to java17

.github/dependabot.yml, .github/workflows/checkov.yml, .github/workflows/dailyPassportSmokeTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/pre-merge-integration-test.yaml, .github/workflows/secure-post-merge.yml
Updates to remove most of the githib action deprecation warnings and updates in preparation for canary deployments rollout
workflows and dependabot changes:
* remove deprecations
* remove rusty actions
* implement dev-platform actions
* add dependabot for workflow actions
Updates to remove most of the githib action deprecation warnings and updates in preparation for canary deployments rollout
- [IPS-477](https://govukverify.atlassian.net/browse/IPS-477)
- [IPS-494](https://govukverify.atlassian.net/browse/IPS-494)
[IPS-477]: https://govukverify.atlassian.net/browse/IPS-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-494]: https://govukverify.atlassian.net/browse/IPS-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> IPS-477 fix lime workflow warnings

.github/workflows/secure-post-merge.yml
The output from the sam build step was missed in the previous update, this is needed to be passed into the dev-platform upload action
To fix build error for build deployment
- [IPS-477](https://govukverify.atlassian.net/browse/IPS-477)
[IPS-477]: https://govukverify.atlassian.net/browse/IPS-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-477 fix missed output from sam build

.github/workflows/pre-merge-checks.yml, build.gradle, lambdas/issuecredential/build.gradle, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/handler/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/utils/Injector.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/utils/MockHttpServer.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/utils/PreLambdaHandler.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ClientFactoryService.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ServiceFactory.java, lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ClientFactoryServiceTest.java
Added contract tests covering VC creation
To allow us to test the contract when we alter the VC
=> Lime 883: Adding VC contract tests for the passport scenarios

acceptance-tests/run-local-tests.sh, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportAPIStepDefs.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportStepDefs.java, acceptance-tests/src/test/resources/features/passport/Passport.feature, acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature, build.gradle, infrastructure/lambda/template.yaml, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ContraIndicatorMapper.java, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ThirdPartyAPIServiceFactory.java, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dcs/DcsThirdPartyAPIService.java, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dvad/DvadAPIHeaderValues.java, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dvad/endpoints/DvadAPIEndpointFactory.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ContraindicationMappingsTest.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dcs/DcsThirdPartyAPIServiceTest.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dvad/DvadThirdPartyAPIServiceTest.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dvad/endpoints/GraphQLRequestServiceTest.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dvad/endpoints/HealthCheckServiceTest.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/services/dvad/endpoints/TokenRequestServiceTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/service/VerifiableCredentialService.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationService.java, lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportConfigurationServiceTest.java
Enabling JTI token field to appear in VC, and adding this check to acceptance checks.
To align with other CRIs and enable use of JTI for unique referencing.
- [LIME-569](https://govukverify.atlassian.net/browse/LIME-569)
[LIME-569]: https://govukverify.atlassian.net/browse/LIME-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Lime 569 adding JTI field to VC

.github/workflows/pre-merge-checks.yml, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/utils/PreLambdaHandler.java
Adding the JTI value to our VC for contract testing to reflect accurate VC.
This change was missed in the initial implementation.
- [LIME-989](https://govukverify.atlassian.net/browse/LIME-989)
[LIME-989]: https://govukverify.atlassian.net/browse/LIME-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-989 adding JTI to contract testing

lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/IssueCredentialHandlerTest.java
Added ability to specify pact version.
To ensure we are pointed at the correct version in future and avoid failing to find pact.
- [LIME-989](https://govukverify.atlassian.net/browse/LIME-989)
[LIME-989]: https://govukverify.atlassian.net/browse/LIME-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-989 adding consumer version for pact testing

acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportStepDefs.java, acceptance-tests/src/test/resources/features/passport/English/Passport.feature
Updated test data creation to remove bulk from pre written test data subjects to allow test data to be written without having to create a new subject
To upgrade and update the test framework
- [LIME-892](https://govukverify.atlassian.net/browse/LIME-892)
[LIME-892]: https://govukverify.atlassian.net/browse/LIME-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Lime 892 - Updated test data creation

acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/OrchestratorStubPage.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportPageObject.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/E2E_PassportStepDefs.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportStepDefs.java, acceptance-tests/src/test/resources/features/passport/English/PassportFullJourneyfeature.feature
Passport E2E tests have been updated to run with the updated orchestrator stub. Also, updated the method validateErrorPageHeading() to use assert for the validation.
=> LIME-1056 Update the E2E tests in passport that are failing due to the changes in orchestrator stub

acceptance-tests/src/test/resources/features/passport/English/Passport.feature, acceptance-tests/src/test/resources/features/passport/PassportCRIAPI.feature
Added the tag @stub to all the tests that have the @build tag against them. Also added the tag @uat to all the tests that have @staging tag against them.
I have also removed the test tags that are not in use.
=> LIME-982 Passport: Update test tags so we are swapping build and staging

build.gradle
Upgrading version changes for powertools in build.gradle, and using the same version throughout. AWS Metric version removed so to rely on powertools.
- [LIME-1190](https://govukverify.atlassian.net/browse/LIME-1190)
[LIME-1190]: https://govukverify.atlassian.net/browse/LIME-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1190 Update powertools to 1.18.0

build.gradle, infrastructure/lambda/template.yaml, lambdas/certexpiryreminder/build.gradle, lambdas/certexpiryreminder/src/main/java/uk/gov/di/ipv/cri/passport/certexpiryreminder/handler/CertExpiryReminderHandler.java, lambdas/checkpassport/build.gradle, lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/services/ThirdPartyAPIServiceFactory.java, lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/handler/CheckPassportHandlerTest.java, lambdas/issuecredential/build.gradle, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/handler/IssueCredentialHandler.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/pact/IssueCredentialHandlerTest.java, lib-dvad/build.gradle, lib-dvad/src/main/java/uk/gov/di/ipv/cri/passport/library/dvad/services/DVADCloseableHttpClientFactory.java, lib-dvad/src/test/java/uk/gov/di/ipv/cri/passport/library/dvad/services/DVADCloseableHttpClientFactoryTest.java, lib/build.gradle, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ApacheHTTPClientFactoryService.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ParameterStoreService.java, lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ServiceFactory.java, lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ApacheHTTPClientFactoryServiceTest.java, lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ParameterStoreServiceTest.java, lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ServiceFactoryTest.java
Tracking the same changes for Fraud API - https://github.com/govuk-one-login/ipv-cri-fraud-api/pull/302 and https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/320
Removed ClientFactoryService, and switch to CRI Lib ClientProviderFactory.
Align with contructor changes in CRI Lib services.
Added netty-http client to the build exclusions and placed them in the each lambda sub project (to fully take effect)
Remove versions specified for the main Jackson dependencies and defer to the ones pull in from software.amazon.awssdk:bom.
There is a breakage in a later jackson version, which crashes in the sdk classes which expect the older versions.
Note : jackson-datatype-jsr310 and jackson-datatype-jdk8 are not in the aws sdk and are custom dependencies these version have been set at the …
=> LIME-1071 Update to CRI 3.0.2 and align with service changes

acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java
to include assertion around the vcHeader values returned (kid, typ, alg) on the response headers from the credential/issue endpoint
Updated the pre-merge API tests to include assertion around the vcHeader values returned (kid, typ, alg) on the response headers from the credential/issue endpoint
To ensure that the correct header values are always validated against when calling the credential/issue endpoint
- [LIME-1201](https://govukverify.atlassian.net/browse/LIME-1201)
[LIME-1245]: https://govukverify.atlassian.net/browse/LIME-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1201]: https://govukverify.atlassian.net/browse/LIME-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1245 - Updated pre-merge API tests

build.gradle, lib-dvad/src/main/java/uk/gov/di/ipv/cri/passport/library/dvad/services/DVADCloseableHttpClientFactory.java
Updated parameter names
To safely perform cert rotation in production
=> LIME-1281: Making changes for hmpo prod cert rotation

.github/dependabot.yml
Minor fix to dependabot grouping format to ensure grouping works. 
Previous format believed to be incorrect
- [LIME-1229](https://govukverify.atlassian.net/browse/LIME-1229)
[LIME-1229]: https://govukverify.atlassian.net/browse/LIME-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1229 minor fix to dependabot grouping

acceptance-tests/src/test/resources/features/passport/English/Passport.feature
Disable broken ac test
To unblock Pipeline
- Ticket raised LIME-1578
- [LIME-1538](https://govukverify.atlassian.net/browse/LIME-1538)
[LIME-1538]: https://govukverify.atlassian.net/browse/LIME-1538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1538 Disable broken ac test

.secrets.baseline, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PassportAPIPage.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/PassportAPIStepDefs.java, acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/utilities/BrowserUtils.java, acceptance-tests/src/test/resources/features/passport/English/Passport.feature
Clean up, addressing comments left on this pr - https://github.com/govuk-one-login/ipv-cri-uk-passport-api/pull/479
=> LIME-1767 - Test Clean up

.github/workflows/post-merge-package-for-build.yml
Corrected commit SHA for devplatform-upload-action
commit SHA was incorrect when LIME-1909 was initially merged
- [LIME-1909](https://govukverify.atlassian.net/browse/LIME-1909)
[LIME-1909]: https://govukverify.atlassian.net/browse/LIME-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1909 fix SHA in package for build action
